function create_geo_file(dim, geo_file_name, h)
    if nargin < 2
        h = 0.3;
    end

    file_begin = [...
    '/*********************************************************************' newline ...
    ' *' newline ...
    ' *  Gmsh geometry file, generate by matlab.' newline ...
    ' *' newline ...
    ' *  Constructive Solid Geometry, OpenCASCADE geometry kernel' newline ...
    ' *' newline ...
    ' *********************************************************************/' newline ...
    '' newline ...
    'SetFactory("OpenCASCADE");' newline ...
    '' newline ];
    
    fid = fopen(geo_file_name, 'w');
    fprintf(fid, file_begin);
    if dim == 2
        geo2d(fid, h)
    elseif dim == 3
        geo3d(fid, h)
    else
        error('dim  must be 2 or 3');
    end
    fclose(fid);
end

function geo2d(fid, h)
    file_middle = [...
        'lc = %g;' newline ...
        'Point(1) = {0, 1, 0, lc};' newline ... 
        'Point(2) = {1, 1, 0, lc};' newline ...
        'Point(3) = {1, 0, 0, lc};' newline ...
        'Point(4) = {0, 0, 0, lc};' newline ...
        'Line(1) = {1, 2};' newline ...
        'Line(2) = {2, 3};' newline ...
        'Line(3) = {3, 4};' newline ...
        'Line(4) = {4, 1};' newline ...
        'Line Loop(6) = {4, 1, 2, 3};' newline ...
        'Plane Surface(6) = {6};' newline ];
    fprintf(fid, file_middle, h);
end

function geo3d(fid, h)
%     p0 = [0, 0, 0];
%     p1 = [1, 1, 1];
%     p2 = [1/2, 1/2, 1/2];
% 
%     file_middle = [...
%         'Box(1) = {%g,%g,%g, %g,%g,%g};' newline ...
%         'Box(2) = {%g,%g,%g, %g,%g,%g};' newline ...
%         'BooleanDifference(3) = { Volume{1}; Delete; }{ Volume{2}; Delete; };' newline ...
%         '' newline ...
%         'lc = %g;' newline ...
%         'Characteristic Length{ PointsOf{ Volume{:}; } } = lc;'];
%     fprintf(fid, file_middle, p0, p1, p0, p2, h);
    file_middle = [...
            'Box(1) = {0,0,0, 1,1,1};' newline ...
            'lc = %g;' newline ...
            'Characteristic Length{ PointsOf{ Volume{:}; } } = lc;'];
    fprintf(fid, file_middle, h);
end







